apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv0
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data0"
