apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv0
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv1
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv2
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data3"
